### ISSUE TITLE
Not waking up

### ISSUE THREAD

**Issue by aquada** [mafrosis/Wake-On-Lan#13]
Server: Linux Mint 17.1
Phone: Samsung Gio

I configure IP and MAC address correctly, but this does not wake up the server. I have a a proprietary Android app which works on the same phone waking the same server.

Not sure what information I can give you, but happy to provide it

**Comment by mafrosis** [comment]
Hey thanks for reporting the issue. It's nigh impossible to debug these things without having your setup and wireshark handy, so I'll probably just have to leave it.

I'll leave the issue open on the off chance that I get around to putting some time into WakeOnLan for Android..

**Comment by juliankotrba** [comment]
I had the same problem. Solved it by using broadcast instead of computers ip.
Hope this helps. 
Cheers j

**Comment by mafrosis** [comment]
Hey @alleyoopster it's a good point that @juliankotrba raises here - what IP address are you putting into the app?

I could feasibly guess the broadcast IP for the current network and spam out a few wol packets, that would help with people who put in the wrong IP...

**Comment by aquada** [comment]
I will try it with broadcast address and report back. I think I already tried with 192.168.0.255 (subnet 255.255.255.0). Maybe I need to make it 255.255.255.255

I was using the IP address of the computer that needed waking 192.168.0.222

EDIT: Good call with the broadcast. Setting IP to 255.255.255.255 works. maybe this could be made default? Many thanks!
