### ISSUE TITLE
Homescreen shortcut for a host

### ISSUE THREAD

**Issue by mafrosis** [mafrosis/Wake-On-Lan#5]
Similar to ConnectBot's effort.

Thanks John Gorena.

**Comment by yohan-pereira** [comment]
Hi, I would like to give this a shot. I noticed you have a branch for it, are there any technical limitations/quirks I need to be aware of?

**Comment by mafrosis** [comment]
Hey that would be awesome. It was quite a while back that I did that work, so I can't really remember what I did, or why I couldn't get it to work. It may be that since ICS it's simple!

I just rebased that shortcut branch against master so it's up to date with the current release code. (Bad practice perhaps, but ho hum).

Let me know if there's anything I can do to help.

**Comment by yohan-pereira** [comment]
Hi, I've got something working, albeit it needs a bit of polishing and testing. After reading the code in your shortcut branch, I realised I was taking a slightly different approach, so I created a new branch called single-shortcut in my repository. 

In my approach the user can add a shortcut to a single HistoryItem to the home screen as opposed to having the entire history list as a widget (which I think is what you were working towards). I do see the merits of both approaches and will try and implement a second widget which shows a list using the code in the shortcut branch.

Currently when the user adds a wakeonlan widget to their home screen, the HistoryList widget is shown allowing them to select a HistoryItem. Once selected a shortcut to the corresponding HistoryItem is created on the homescreen. Clicking the shortcut sends a packet to the configured host.

I've tested this on my stock nexus 4 and nexus 7. Haven't tested this on older android releases yet. 

![screenshot_2013-07-16-13-06-04](https://f.cloud.github.com/assets/3246529/803418/e72b2f00-edf0-11e2-8127-78fe3ec3231f.png)

**Comment by mafrosis** [comment]
Hey Yohan, great work. I think the way you've built it now is definitely the right way to go - don't worry about implementing another list-based widget; simple is best.

I'll build a debug version and test it on a few versions of Android. I've got an old 2.3.3 phone so we can cover that off - and I'll also test 1.6 on the emulator.

**Comment by mafrosis** [comment]
@yohan-pereira Hey dude, can you raise a pull request on your branch please? That makes it easier for me to review your changes. Thanks

**Comment by yohan-pereira** [comment]
Done. Sorry about that I'm new here :)
There is one issue that needs to be addressed, I've described it in my pull request.

**Comment by mafrosis** [comment]
Closed in #9
